apiVersion: apps/v1
kind: Deployment
metadata:
  name: alex-brot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alex-brot-backend
  template:
    metadata:
      labels:
        app: alex-brot-backend
    spec:
      containers:
        - name: alex-brot-backend
          image: ghcr.io/alex-brot/alex-brot-backend:latest
          imagePullPolicy: Always
          env:
            - name: BUILD_PROD
              value: production
            - name: NODE_ENV
              value: production # https://github.com/medusajs/medusa/issues/10147
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: alex-brot-postgres-app
            - name: ADMIN_CORS
              value: https://medusa.alex-brot.stenz.dev
            - name: S3_FILE_URL
              valueFrom:
                secretKeyRef:
                  key: s3-file-url
                  name: alex-brot-secrets
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: s3-access-key-id
                  name: alex-brot-secrets
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: s3-secret-access-key
                  name: alex-brot-secrets
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  key: s3-region
                  name: alex-brot-secrets
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  key: s3-bucket
                  name: alex-brot-secrets
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: s3-endpoint
                  name: alex-brot-secrets
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: stripe-api-key
                  name: alex-brot-secrets
            - name: REDIS_URL
              value: redis://valkey-primary.alex-brot.svc.cluster.local:6379

---
apiVersion: v1
kind: Service
metadata:
  name: alex-brot-medusa
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: alex-brot-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alex-brot
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: medusa.alex-brot.stenz.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alex-brot-medusa
                port:
                  number: 9000
  tls:
    - secretName: alex-brot-backend-tls
      hosts:
        - medusa.alex-brot.stenz.dev
