apiVersion: apps/v1
kind: Deployment
metadata:
  name: alex-brot-storefront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alex-brot-storefront
  template:
    metadata:
      labels:
        app: alex-brot-storefront
    spec:
      containers:
        - name: alex-brot-storefront
          image: ghcr.io/alex-brot/alex-brot-storefront:latest
          imagePullPolicy: Always
          env:
            - name: MEDUSA_BACKEND_URL
              value: https://medusa.alex-brot.stenz.dev
            - name: NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  key: publishable-api-key
                  name: alex-brot-secrets
            - name: NEXT_PUBLIC_DEFAULT_REGION
              value: at
            - name: BLOG_POST_URL
              value: https://strapi.alex-brot.stenz.dev
            - name: BLOG_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: blog-api-token
                  name: alex-brot-secrets
            - name: REVALIDATE_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: blog-revalidate-secret

---
apiVersion: v1
kind: Service
metadata:
  name: alex-brot-storefront
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: alex-brot-storefront
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alex-brot-frontend
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: alex-brot.stenz.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alex-brot-storefront
                port:
                  number: 8000
  tls:
    - secretName: alex-brot-storefront-tls
      hosts:
        - alex-brot.stenz.dev
