apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alex-brot

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: alex-brot-backend
      spec:
        template:
          spec:
            containers:
              - name: alex-brot-backend
                image: ghcr.io/alex-brot/alex-brot-medusa:v0.0.1
  - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: alex-brot-storefront
        spec:
          template:
            spec:
              containers:
                - name: alex-brot-storefront
                  image: ghcr.io/alex-brot/alex-brot-storefront:
