apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alex-brot

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: alex-brot-backend
      spec:
        template:
          spec:
            containers:
              - name: alex-brot-backend
                image: ghcr.io/alex-brot/alex-brot-medusa-dev:13829908390
                env:
                  - name: ADMIN_CORS
                    value: https://medusa.alex-brot.stenz.dev
  - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: alex-brot-storefront
        spec:
          template:
            spec:
              containers:
                - name: alex-brot-storefront
                  image: ghcr.io/alex-brot/alex-brot-storefront-dev:13823009895
                  env:
                    - name: MEDUSA_BACKEND_URL
                      value: https://medusa.alex-brot.stenz.dev
                    - name: BLOG_POST_URL
                      value: https://strapi.alex-brot.stenz.dev
  - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: alex-brot-strapi
        spec:
          template:
            spec:
              containers:
                - name: alex-brot-strapi
                  image: ghcr.io/alex-brot/alex-brot-strapi:13564396659
                  env:
                    - name: BLOG_REVALIDATE_URL
                      value: https://alex-brot.stenz.dev/api/blog/revalidate
