apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alex-brot

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: alex-brot-backend
      spec:
        template:
          spec:
            containers:
              - name: alex-brot-backend
                image: ghcr.io/alex-brot/alex-brot-medusa:v0.0.2
  - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: alex-brot-storefront
        spec:
          template:
            spec:
              containers:
                - name: alex-brot-storefront
                  image: ghcr.io/alex-brot/alex-brot-storefront:11719942797
                  env:
                    - name: NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
                      valueFrom:
                        secretKeyRef:
                          key: publishable-api-key
                          name: alex-brot-secrets
