apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alex-brot-dev

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: alex-brot-backend
      spec:
        template:
          spec:
            containers:
              - name: alex-brot-backend
                image: ghcr.io/alex-brot/alex-brot-medusa-dev:12676782732
                env:
                  - name: MEDUSA_ADMIN_BACKEND_URL
                    value: https://dev.medusa.alex-brot.stenz.dev
  - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: alex-brot-storefront
        spec:
          template:
            spec:
              containers:
                - name: alex-brot-storefront
                  image: ghcr.io/alex-brot/alex-brot-storefront-dev:11938840843
  - path: ingress-patch-medusa.yaml
    target:
      kind: Ingress
      name: alex-brot
  - path: ingress-patch-storefront.yaml
    target:
      kind: Ingress
      name: alex-brot-frontend
