apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alex-brot-dev

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: alex-brot-backend
      spec:
        template:
          spec:
            containers:
              - name: alex-brot-backend
                image: ghcr.io/alex-brot/alex-brot-medusa-dev:12919981136
                env:
                  - name: ADMIN_CORS
                    value: https://dev.medusa.alex-brot.stenz.dev
  - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: alex-brot-storefront
        spec:
          template:
            spec:
              containers:
                - name: alex-brot-storefront
                  image: ghcr.io/alex-brot/alex-brot-storefront-dev:12924644671
                  env:
                    - name: MEDUSA_BACKEND_URL
                      value: https://dev.medusa.alex-brot.stenz.dev
                    - name: NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
                      valueFrom:
                        secretKeyRef:
                          key: publishable-api-key
                          name: alex-brot-secrets
  - path: ingress-patch-medusa.yaml
    target:
      kind: Ingress
      name: alex-brot
  - path: ingress-patch-storefront.yaml
    target:
      kind: Ingress
      name: alex-brot-frontend
